---
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/lines_in_files.yml'
- include_tasks:        '../tasks/commands.yml'
  when:                 install_files_result.changed or lines_in_files_result.changed

